[package]
name = "rust-beep"
version = "0.0.1"
authors = ["Matthias Wimmer <m@tthias.eu>"]
homepage = "https://github.com/mawis"
license = "LGPL-2.1-only"

[dependencies]
log = "0.4.6"

[build-dependencies]
cmake = "0.1"
