[package]
name = "rust-beep"
version = "0.1.0"
authors = ["Matthias Wimmer <m@tthias.eu>"]
homepage = "https://github.com/mawis"
license = "LGPL-2.1-only"

[dependencies]

[build-dependencies]
cmake = "0.1"